### ISSUE TITLE
[Bug]: Two TypeScript versions in the tree — @nestjs/cli pins 5.9.3 exactly

### ISSUE THREAD

**Issue by marinoscar** [marinoscar/EnterpriseAppBase#65]
Part of #44. Split out of PR #57.

### Problem Statement

Two TypeScript versions coexist in the dependency tree and `npm dedupe` cannot collapse them:

```
node_modules/typescript            5.9.3   (hoisted)
apps/api/node_modules/typescript   6.0.3
apps/web/node_modules/typescript   6.0.3
```

The cause is `@nestjs/cli`, which depends on `typescript` at **exactly `5.9.3`** as a regular dependency, not a peer. Nothing in this repository can satisfy both that pin and the workspaces' `^6.0.3`.

Two concrete consequences:

**1. The build and the typecheck use different compilers.** `nest build` compiles with TypeScript 5.9.3 (resolved from `@nestjs/cli`'s own tree), while `npm run typecheck` runs 6.0.3 from the workspace. A construct accepted by one and rejected by the other will produce a green typecheck and a broken build, or vice versa.

**2. It actively misleads tooling and people.** During #44 this caused a subagent to file a false bug report: it invoked `../../node_modules/.bin/tsc` (the hoisted 5.9.3), got `error TS5103: Invalid value for '--ignoreDeprecations'` — because 5.9.3 does not recognise the `"6.0"` value that 6.0.3 accepts — and concluded that `npm run` was silently failing and that typecheck was red on `main`. Neither was true. Any contributor invoking the root `tsc` will hit the same trap.

### Proposed Solution

Options, roughly in order of preference:

1. **Add a root `overrides` entry forcing `typescript` to `^6.0.3`.** One line, collapses the tree. Needs verification that `nest build` still works under TS 6 — `@nestjs/cli` pinned exactly for a reason, so this must be tested, not assumed.
2. **Stop using `nest build`.** Compile with the workspace's own `tsc -p tsconfig.build.json`. The Nest CLI is only used as a build wrapper here — `nest-cli.json` is minimal (no `builder`, no `assets`, no monorepo config), so the CLI adds little beyond `deleteOutDir`. This removes the pin entirely along with `@nestjs/cli`'s heavy `@angular-devkit` tree.
3. **Wait for `@nestjs/cli` to relax the pin** and document the hazard in the meantime.

Option 2 is likely the most durable: `@nestjs/cli` is also the source of the `@angular-devkit/*` packages that pin rxjs to exactly 7.8.1 (the duplication fixed in #48), so removing it resolves two version-pinning problems at once.

### Alternatives Considered

- **Leave it and document it.** Cheapest, but the trap stays live for every contributor and for any agent or script that resolves `tsc` from the root.
- **Pin the workspaces down to 5.9.3.** Rejected — it gives up TypeScript 6 across the project to satisfy a build tool's transitive pin, and TypeScript 7 is already released.

### Affected Component

API (Backend)

### Priority

Important

### Additional Context

Not a security issue and not urgent, which is why it was deliberately left out of #48 and #57. It is, however, a correctness hazard rather than cosmetic: two compilers on one codebase is a silent-divergence risk, and it has already produced one incorrect diagnosis.
